---
anchor-sections: false
---

::: page-content
# [Experience]{style="color:#440712; display:block; text-align:center;"}

## Research Fellow

<!-- another way to write this is <span style="color: #163793;">Research Fellow</span>. This is not necessary here as the color is in the style (custom.css) as heading color-->

**Center of Excellence on Environmental Health and Sustainability, Morehouse School of Medicine, Atlanta, GA**\
*Sept 2025 – Present* 

-   Direct research projects on sustainability, wellness, and environmental health in the built environment.\
-   Produce and deliver reports, dashboards, and presentations to translate research into actionable insights for internal and external audiences.\
-   Drive center board-level planning, sustainability curriculum development, and data tracking, and to support organizational decision-making.\
-   Advance sustainability integration across departmental research, programming, and stakeholder engagement.\

## Data Analysis Intern

**Center of Excellence on Environmental Health and Sustainability, Morehouse School of Medicine, Atlanta, GA**\
*June 2025 - Sept 2025*\

-   Led student team in updating an interactive community health dashboard.\
-   Cleaned, analyzed, and interpreted public health datasets to identify key trends.\
-   Translated complex data into visualizations and reports for stakeholder engagement.\

## Quality Training Specialist

**CSL Plasma**\
*Sept 2022- Aug 2023*\

-   Ensured center-wide compliance with Standard Operating Procedures (SOP)/Work in a CLIA-certified laboratory.\
-   Managed recertification programs, improving compliance accuracy and efficiency.\
-   Conducted investigations, documented regulatory deficiencies, and implemented corrective actions to maintain operational standards.\

## Pheresis Group Lead Phlebotomist

**CSL Plasma**\
*Sept 2020- Sept 2022* 

-   Managed and trained the donor floor employees.\
-   Performed venipuncture and oversaw donor safety during pheresis.\
:::
